services:
  - type: web
    name: futsal-gym-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: Futsalgymbot
        sync: false
      - key: WEBHOOK_SECRET
        value: "missecret"
